export const copy = {
  locale: 'en-ET',
  currencyCode: 'ETB',
  currencySymbol: 'ETB',
  dashboard: {
    title: 'Today at a Glance',
    subtitle:
      'A fast view of sales, spending, profit, and what needs restocking.',
    salesLabel: "Today's Sales",
    expensesLabel: "Today's Expenses",
    profitLabel: 'Profit',
    detailsTitle: 'Need details?',
    detailsText: 'Open the activity history to audit each sale and expense entry.',
    openReports: 'Open Reports',
    lowStockTitle: 'Low Stock Alerts',
    lowStockAction: 'Reorder Soon',
    stockLeft: (quantity: number) => `${quantity} left`,
  },
  products: {
    title: 'Products',
    subtitle: 'Your inventory master list with pricing and stock levels.',
    addAction: '+ Add',
    addButton: 'Save Product',
    cancelAction: 'Back',
    buyLabel: 'Buy',
    sellLabel: 'Sell',
    quantityUnit: 'pcs',
    stockPlaceholder: 'Starting quantity',
    formTitle: 'Add Product',
    namePlaceholder: 'Product name',
    emptyState: 'No products yet. Add the first item for the shop.',
    costPlaceholder: 'Cost price',
    sellPlaceholder: 'Selling price',
    filterLabel: 'Filter by category',
    allCategories: 'All',
    categoryField: 'Category',
    formSubtitle: 'Capture the product basics first. We can extend attributes later.',
  },
  sell: {
    title: 'New Sale',
    subtitle: 'Keep this flow fast for the counter. Search, enter quantity, confirm.',
    confirmButton: 'Confirm Sale',
    selectProduct: 'Select Product',
    searchPlaceholder: 'Search product',
    saleDetails: 'Sale Details',
    quantitySold: 'Quantity Sold',
    actualSoldPrice: 'Actual Sold Price',
    expectedTotal: 'Expected total',
    inStock: 'in stock',
    sellingAt: 'Selling at',
    emptyState: 'Add products first before recording a sale.',
    helper: 'Tap a product below to load it into the sale form.',
    successMessage: 'Sale recorded.',
  },
  expenses: {
    title: 'Expenses',
    subtitle: 'Track spending so the profit numbers stay honest.',
    saveButton: 'Save Expense',
    addTitle: 'Add Expense',
    whatDidYouBuy: 'What did you buy?',
    howMuch: 'How much?',
    recentTitle: 'Recent Expenses',
    successMessage: 'Expense saved.',
  },
  reports: {
    title: 'Reports',
    subtitle: 'A simple audit trail of sales and expenses.',
    historyTitle: 'History',
    backButton: 'Back to Dashboard',
    emptyState: 'No activity yet.',
  },
  tabs: {
    home: 'Home',
    products: 'Products',
    sell: 'Sell',
    expenses: 'Expenses',
  },
} as const;
