export const copy = {
  locale: 'en-ET',
  currencyCode: 'ETB',
  currencySymbol: 'ETB',
  dashboard: {
    title: 'Today at a Glance',
    subtitle:
      'A fast view of sales, spending, profit, and what needs restocking.',
    salesLabel: "Today's Sales",
    expensesLabel: "Today's Expenses",
    profitLabel: 'Profit',
    detailsTitle: 'Need details?',
    detailsText: 'Open the activity history to audit each sale and expense entry.',
    openReports: 'Open Reports',
    lowStockTitle: 'Low Stock Alerts',
    lowStockAction: 'Reorder Soon',
    stockLeft: (quantity: number) => `${quantity} left`,
  },
  products: {
    title: 'Products',
    subtitle: 'Your inventory master list with pricing and stock levels.',
    addButton: '+ Add Product',
    buyLabel: 'Buy',
    sellLabel: 'Sell',
    quantityUnit: 'pcs',
  },
  sell: {
    title: 'New Sale',
    subtitle: 'Keep this flow fast for the counter. Search, enter quantity, confirm.',
    confirmButton: 'Confirm Sale',
    selectProduct: 'Select Product',
    searchPlaceholder: 'Search product',
    saleDetails: 'Sale Details',
    quantitySold: 'Quantity Sold',
    expectedTotal: 'Expected total',
    inStock: 'in stock',
    sellingAt: 'Selling at',
  },
  expenses: {
    title: 'Expenses',
    subtitle: 'Track spending so the profit numbers stay honest.',
    saveButton: 'Save Expense',
    addTitle: 'Add Expense',
    whatDidYouBuy: 'What did you buy?',
    howMuch: 'How much?',
    recentTitle: 'Recent Expenses',
  },
  reports: {
    title: 'Reports',
    subtitle: 'A simple audit trail of sales and expenses.',
    historyTitle: 'History',
    backButton: 'Back to Dashboard',
  },
  tabs: {
    home: 'Home',
    products: 'Products',
    sell: 'Sell',
    expenses: 'Expenses',
  },
} as const;
